name: android_id_example
description: Demonstrates how to use the android_id plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  android_id:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
