name: Flutter checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  check_pub_dependencies:
    name: Check dependencies
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        timeout-minutes: 10
        run: flutter pub get

  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Check Dart formatting
        timeout-minutes: 10
        run: dart format --page-width 120 --set-exit-if-changed .

  analyze:
    name: Dart analyze
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Run Dart analyze
        timeout-minutes: 10
        uses: invertase/github-action-dart-analyzer@v3.0.0

  test:
    name: Flutter test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter test
        timeout-minutes: 10
        run: flutter test

  test_example:
    name: Flutter test example
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Flutter pub get
        run: |
          cd example
          flutter pub get

      - name: Flutter test example
        timeout-minutes: 10
        run: |
          cd example
          flutter test
