name: Check pub score

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-score:
    name: Check pub score
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install pana
        run: dart pub global activate pana

      - name: Check pub score
        run: dart pub global run pana --exit-code-threshold 0 .
